# Generated by Django 3.0.7 on 2021-05-25 04:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 25, 4, 20, 37, 960367, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
