# Generated by Django 3.0.7 on 2021-05-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
